baseURL: https://eternity.bora.sh # todo: change site url.
title: Искусство балета # todo: change site name.
defaultContentLanguage: 'ru'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: Мы предлагаем ненадолго окунуться в атмосферу классического балета. # todo: change default subtitle for your website.
  copyright: Все права защищены. # todo: set your copyright type.
  author: GurFoto.Ru, Юрий Гуревич # todo: set your full name.
  dontShowSource: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:eternity@bora.sh'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/boratanrikulu/eternity'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.bora.sh/eternity'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://linkedin.bora.sh/in/eternity'
  homepage: "/ballet" # homepage link, mostly same with menu.main[0]
  specialPages:
    - ballet
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false
  enterBtn: "Входите"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: ballet
      params:
        itemTitle: "балет"
      url: /ballet/
      weight: 1
    - name: people
      params:
        itemTitle: "люди"
      url: /tags/people/
      weight: 2
    - name: nature
      params:
        itemTitle: "природа"
      url: /tags/nature/
      weight: 3
    - name: archive
      params:
        itemTitle: "архив"
      url: /tags/archive/
      weight: 4
    - name: about
      params:
        itemTitle: "о нас"
      url: /about/
      weight: 5
